regenerate icons, because somehow it blocked compiling the tauri app:
error: proc macro panicked
  --> src/main.rs:15:14
   |
15 |         .run(tauri::generate_context!())
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: icon tauri-emoji-mart-app/src-tauri/icons/32x32.png is not RGBA